---

- name: Install Java
  hosts: hadoop
  become: True
  remote_user: centos
  gather_facts: no
  roles:
#    - Java

- name: Initial Common Setup
  hosts: hadoop
  become: True
  remote_user: centos
  gather_facts: yes
  roles:
    - hdp_common
